# -*- coding: utf-8 -*-
"""UAS_Machine Learning_Decision Tree_RezaFirchansyah_171011400242.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MgyNg9nf1isF_j9_2wHCYjLfK3P9NYyL
"""

from sklearn import tree

clf = tree.DecisionTreeClassifier()

X = [[181, 80, 44], [177, 70, 43], [160, 60, 38], [154, 54, 37], [166, 65, 40], [190, 90, 47], [175, 64, 39], 
     [177, 70, 40], [159, 55, 37], [171, 75, 42], [181, 85, 43] ]
X

Y = ['male', 'male', 'female', 'female', 'male', 'male', 'female', 'female', 'female', 'male', 'male']
Y

clf = clf.fit(X,Y)

prediction = clf.predict([[150, 45, 22]])
print(prediction)